### ISSUE TITLE
Overflow to disk

### ISSUE THREAD

**Issue by usrflo** [openCage/memoryfs#6]
In my project https://github.com/usrflo/encfs4j I'd like to opt. save temporary files in memory. memoryfs could be appropriate for this. If free memory is exceeded I would like to use a transparent optional overflow to disk ;)

**Comment by openCage** [comment]
I'd rather keep memoryfs a pure in-memory filesystem. But your usecase is valid. It could be implemented easily with my other project eightyfs ontop of memoryfs. Eightyfs takes the pain out of virtual filesystem implementation.
